services:
  laracy_cli:
    container_name: laracy_cli
    build:
      context: ./docker/cli
      dockerfile: Dockerfile
      target: laracy_cli
      args:
        - PHP_VERSION=${PHP_VERSION:-7.3}
        - NODE_VERSION=${NODE_VERSION:-16}
        - PHP_EXTENSIONS=${PHP_EXTENSIONS:-}
    profiles:
      - cli
    volumes:
      - ${LARAVEL_ROOT:-./my-laravel-project}:/app
  laracy_server:
    container_name: laracy_server
    build:
      context: ./docker/server
      dockerfile: Dockerfile
      target: laracy_server
      args:
        - PHP_FPM_VERSION=${PHP_FPM_VERSION:-7.3}
        - PHP_FPM_EXTENSIONS=${PHP_FPM_EXTENSIONS:-}
    ports:
      - "${NGINX_PORT:-80}:80"
    profiles:
      - server
    volumes:
      - ${LARAVEL_ROOT:-./my-laravel-project}:/var/www/html/laravel
  laracy_integrate_cli:
    container_name: laracy_integrate_cli
    build:
      context: ./docker/cli
      dockerfile: Dockerfile
      target: laracy_integrate_cli
      additional_contexts:
        source_path: ${LARAVEL_ROOT:-./my-laravel-project}
    profiles:
      - integrate_cli
  laracy_integrate_server:
    container_name: laracy_integrate_server
    build:
      context: ./docker/server
      dockerfile: Dockerfile
      target: laracy_integrate_server
      additional_contexts:
        source_path: ${LARAVEL_ROOT:-./my-laravel-project}
    profiles:
      - integrate_server
